/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NestedRouteImport } from './routes/nested'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NestedChildRouteImport } from './routes/nested/child'

const NestedRoute = NestedRouteImport.update({
  id: '/nested',
  path: '/nested',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NestedChildRoute = NestedChildRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => NestedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/nested': typeof NestedRouteWithChildren
  '/nested/child': typeof NestedChildRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/nested': typeof NestedRouteWithChildren
  '/nested/child': typeof NestedChildRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/nested': typeof NestedRouteWithChildren
  '/nested/child': typeof NestedChildRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/nested' | '/nested/child'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/nested' | '/nested/child'
  id: '__root__' | '/' | '/about' | '/nested' | '/nested/child'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  NestedRoute: typeof NestedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nested': {
      id: '/nested'
      path: '/nested'
      fullPath: '/nested'
      preLoaderRoute: typeof NestedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nested/child': {
      id: '/nested/child'
      path: '/child'
      fullPath: '/nested/child'
      preLoaderRoute: typeof NestedChildRouteImport
      parentRoute: typeof NestedRoute
    }
  }
}

interface NestedRouteChildren {
  NestedChildRoute: typeof NestedChildRoute
}

const NestedRouteChildren: NestedRouteChildren = {
  NestedChildRoute: NestedChildRoute,
}

const NestedRouteWithChildren =
  NestedRoute._addFileChildren(NestedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  NestedRoute: NestedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
