/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DetailRouteImport } from './routes/detail'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DetailMoreRouteImport } from './routes/detail.more'
import { Route as DetailInfoRouteImport } from './routes/detail.info'

const DetailRoute = DetailRouteImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailMoreRoute = DetailMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => DetailRoute,
} as any)
const DetailInfoRoute = DetailInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => DetailRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/detail': typeof DetailRouteWithChildren
  '/detail/info': typeof DetailInfoRoute
  '/detail/more': typeof DetailMoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/detail': typeof DetailRouteWithChildren
  '/detail/info': typeof DetailInfoRoute
  '/detail/more': typeof DetailMoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/detail': typeof DetailRouteWithChildren
  '/detail/info': typeof DetailInfoRoute
  '/detail/more': typeof DetailMoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/detail' | '/detail/info' | '/detail/more'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/detail' | '/detail/info' | '/detail/more'
  id: '__root__' | '/' | '/detail' | '/detail/info' | '/detail/more'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetailRoute: typeof DetailRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/detail': {
      id: '/detail'
      path: '/detail'
      fullPath: '/detail'
      preLoaderRoute: typeof DetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail/more': {
      id: '/detail/more'
      path: '/more'
      fullPath: '/detail/more'
      preLoaderRoute: typeof DetailMoreRouteImport
      parentRoute: typeof DetailRoute
    }
    '/detail/info': {
      id: '/detail/info'
      path: '/info'
      fullPath: '/detail/info'
      preLoaderRoute: typeof DetailInfoRouteImport
      parentRoute: typeof DetailRoute
    }
  }
}

interface DetailRouteChildren {
  DetailInfoRoute: typeof DetailInfoRoute
  DetailMoreRoute: typeof DetailMoreRoute
}

const DetailRouteChildren: DetailRouteChildren = {
  DetailInfoRoute: DetailInfoRoute,
  DetailMoreRoute: DetailMoreRoute,
}

const DetailRouteWithChildren =
  DetailRoute._addFileChildren(DetailRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetailRoute: DetailRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
